<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="Grpc.Net.Client" />
    <ProjectReference Include="../mk8.dns.Contracts/mk8.dns.Contracts.csproj" />
  </ItemGroup>
</Project>
