<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <ProjectReference Include="../mk8.dns.Transport/mk8.dns.Transport.csproj" />
    <ProjectReference Include="../mk8.dns.Application.BLL/mk8.dns.Application.BLL.csproj" />
    <ProjectReference Include="../mk8.dns.Infrastructure/mk8.dns.Infrastructure.csproj" />
    <ProjectReference Include="../mk8.dns.Engine.Recursive/mk8.dns.Engine.Recursive.csproj" />
    <ProjectReference Include="../mk8.dns.Engine.Authoritative/mk8.dns.Engine.Authoritative.csproj" />
    <ProjectReference Include="../mk8.dns.Engine.Dnssec/mk8.dns.Engine.Dnssec.csproj" />
    <ProjectReference Include="../mk8.dns.Infrastructure.Cryptography/mk8.dns.Infrastructure.Cryptography.csproj" />
    <ProjectReference Include="../mk8.dns.Operator/mk8.dns.Operator.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="../mk8.dns.Application.DAL/mk8.dns.Application.DAL.csproj" />
    <ProjectReference Include="../mk8.dns.Wire/mk8.dns.Wire.csproj" />
    <ProjectReference Include="../mk8.dns.Application/mk8.dns.Application.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="../mk8.dns.Gateway/mk8.dns.Gateway.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
