<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="../mk8.dns.Application.BLL/mk8.dns.Application.BLL.csproj" />
    <ProjectReference Include="../mk8.dns.Application.DAL/mk8.dns.Application.DAL.csproj" />
    <ProjectReference Include="../mk8.dns.Configuration/mk8.dns.Configuration.csproj" />
    <ProjectReference Include="../mk8.dns.Transport/mk8.dns.Transport.csproj" />
  </ItemGroup>
</Project>
